### ISSUE TITLE
Revoke should decrease number of total issuances

### ISSUE THREAD

**Issue by ujmappa** [StarbeamOne/home#111]
When user revokes an inventory with many issuances while some of them are already bought, the total number of issues should be decreased and display only the available number, not the grand total (including those with revoked state)

**Comment by Mike-E-angelo** [comment]
Horray you made it :)  Thank you for the discussion. 🙏

So keep in mind that a definition acts as a printing plate, so numerous issuances can be created with the same definition.  Let's say you create 1 issuance with four licenses and two are recalled because you notice a mistake (making the two sold true collector items).  Now you reissue with a 2nd issuance with two licenses.  What should the index of those be?

**Comment by ujmappa** [comment]
Maybe I used the wrong terms, trying to keep up. So, definition, first issuance with 5 licenses. 3 are sold, 2 months passes and noone else is interested anymore, so I revoke the issuance, which means that 2 licenses are revoked. So there are no more 5 licenses available, but only 3, and 3 of them are sold (now it displays 3/5)

**Comment by Mike-E-angelo** [comment]
No worries there are a lot of moving pieces and considerations here.

You are referencing one scenario, which is "I tried to sell and now I have remaining inventory that I no longer want utilizing capacity."

The other scenario is "I sold but now I realize I made a mistake that I want to correct it."  So you issued 5, sold 3, recalled 2, and now are going to issue 2 more.  There are technically 5 licenses that still exist and now you are going to issue 2 more in addition to this, for a total of 7 total licenses for the history of the product:

Issuance #1:
1 of 5: Sold
2 of 5: Sold
3 of 5: Sold
4 of 5: Recalled
5 of 5: Recalled

Issuance #2:
1 of 2: New
2 of 2: New

All licenses for the product:
1 of 7: Sold
2 of 7: Sold
3 of 7: Sold
4 of 7: Recalled
5 of 7: Recalled
6 of 7: New
7 of 7: New

If we adopted your suggested numbering then we would be displaying `6/7` as `4/5`, which is misleading when you start poking through the license explorer to see that there is a `4/7` that has been recalled, effectively making two #4's when there should be only one.  

We may simplify one scenario but also confuse another.  Make sense?

Ideally, we want to signify 3 of 5 active, with 2 recalled for a total of 7, in an easy-to-read way that is also accurate to the state of all issuances to a product.  I am open to further discussion/suggestions.

**Comment by ujmappa** [comment]
Maybe you did not get me, those should not be there in license explorer as well, only history should display those two which have been recalled. Really simple, I go to the market, wanna sell 5 apples. I sell 3, but after a while I make up my mind and I recall the remaining apples. Noone knows what happened to them, maybe I ate them, maybe I threw them out. Next day I go to the market with two other apples. So there are 7 apples, that's true, but from the perspective of the market and buyers there are only 5 apples. It's like I would have decreased the number of available licenses to 3 (which I can only do with recall)

**Comment by Mike-E-angelo** [comment]
I understand your reasoning about apples but this is not an apples-to-apple comparison it's more apples-to-oranges or apples-to-licenses comparison. :)

Please keep in mind that every license is uniquely and sequentially numbered starting from #1.  Licenses are never destroyed and continue to exist after recall.  There has been a suggestion that licenses can be repurposed at some point, and I like this as a potential story as the artist could conceivably sell the destroyed (or otherwise) license to another artist for an amount and receive royalties from the repurposed license.

If you remove the license from the explorer, you will see missing numbers as you explore and this is also disorienting.  

If we start with market comparisons, what happens when a comic book issuance is recalled?  Or a newspaper issuance?  Our model is much more aligned with this than apples.  Except where the physical does not uniquely and sequentially number the objects being sold, we do.  Printing issuances will have a general number (e.g. "First printing", "Second printing").  If you have a 2nd printing that went poorly and issue a 3rd, it will say "3rd printing" when the 2nd is nowhere to be found.  This is the same concept we're carrying over here.

**Comment by ujmappa** [comment]
And the numbering should be:

Issue #1 No. 1 Sold
Issue #1 No. 2 Sold
Issue #1 No. 3 Sold
Issue #1 No. 4 Revoked
Issue #1 No. 5 Revoked
Issue #2 No. 1 New
Issue #2 No. 2 New

This holds more information, and is not confusing at all

**Comment by ujmappa** [comment]
Actually I was also thinking of a book example. The publisher prints 500 books for the first time. 300 are bought, but the publisher withholds 200, revokes and _destroys_ them. Yes, current revoke is _destroy_. So you own one book of 500 or you own own book of 300? You own one of 300. And when the publisher decides to go with a second print of the same book, the numbering starts from 1, under the second, and not from 300 or 500.

**Comment by Mike-E-angelo** [comment]
> You own one of 300

You own 1 of 300 _actively_ issued.  But you _also_ own 1 of 500 _total_ issued. :)  Unlike the physical counterpart, we keep the total history of the product, which is a benefit and convenience of a digital paradigm.  There are still a total of 500 that were ever created for the product, and the history of each and every one of them should be preserved.  There are two ways of looking at it, and we're looking for an elegant way of denoting this.  I can be talked into doing it by the issuance, but we still need to account for the total issued for that issuance, vs active (non-recalled/revoked).

**Comment by ujmappa** [comment]
You own 1 of 300. And the nerds will also mention, that yeah, there were 500 of them, but 200 were burnt. That is history.

**Comment by Mike-E-angelo** [comment]
And indeed those nerds can use the License Explorer to verify exactly that history 🤓

**Comment by ujmappa** [comment]
I can just repeat myself how should the numbering look like in License explorer.

**Comment by Mike-E-angelo** [comment]
If you [are referencing this](https://github.com/StarbeamOne/home/issues/111#issuecomment-1759410292), it still misses the key information of the total issued.  It also seems to imply that you are willing to count the recalled/revoked after all.

Playing devil's advocate here, what happens when we want to allow artists to selectively revoke (liking this word better :D ) a license for repurposing (or other as-yet-identified) purposes?  Let's say someone really really likes the number 6 above and wants to purchase it from the artist for repurposing purposes.  #7 still lives, but what is its displayed index now that #6 has been plucked?  🤔

Along such lines, there is a difference between what is in the license explorer, and how we convey this information in notifications and references throughout the site.

**Comment by ujmappa** [comment]
I do not want to count them. You want to count them, and I showed an example where and how should be counted. You are also wrong with total count of 7. It is 5 (reduced to 3 which should be displayed on the market) and 2.

Artists should not selectively revoke things, and that's it. Other systems don't give a shit about 1, 2, 3, etc. license, you brought one of it, and that's all. But okay, we like numbers, numbered books also contain it, so I am okay with that. But revoking by numbers is bit too much. The system is overcomplicated anyways, do you really want to go that deep?

**Comment by Mike-E-angelo** [comment]
> It is 5 (reduced to 3 which should be displayed on the market) and 2.

It is 5 _active_ and 7 _total_.  There are two spectrums of thought here. :)

> Artists should not selectively revoke things, and that's it

But what if they ask for it like you are asking for changes here? 🤔

> Other systems don't give a shit about 1, 2, 3, etc. license

Other systems do not even think in terms of licenses. 🙃

> The system is overcomplicated anyways, do you really want to go that deep?

And to think you fought me to bring the discussion here 😅

**Comment by ujmappa** [comment]
No, it is not 7 total. It is 3 and 2 active, 5 and 2 total. First print and second print are not the same and cannot be counted together. 

"But what if they ask for it like you are asking for changes here?" - Just let them issue it on GitHub and argue with them 8 hours long, then they will think: "okay, f*** you, it's your system, why should I bother". I am trying to convince you how real life works, but you really insist on these are not apples. But they are.

**Comment by Mike-E-angelo** [comment]
> First print and second print are not the same and cannot be counted together.

They can and they are though.  It's the same product (line) issued twice.  There is a definite line of logical sequencing that can and is captured.

>  I am trying to convince you how real life works,

You are attempting to convince me of your perspective of how real life works.  And I appreciate it.  I am also attempting to reconcile with my own perspective that is backed by deployed and functioning code.  Discussions are necessary to determine how to approach and possible adjustments and/or improvements considering the reality of the situation.  I do not consider this an argument at all.

**Comment by ujmappa** [comment]
Well, okay. I have a book from first print that has 500 copies. The second print had 1000 copies. Now if someone would tell me, that I own one of 1500 copies, I will tell him to go to hell. Especially because the first print has a value of x5 compared to second. Where are your precious numbers here? :) First prints value more than second, even if it is the same product. Like you would say that an exact re-print of a medieval codex can be counted with the medieval codex itself.

Discussions are neccessary, but overcomplication of things is not, because it will completely destroy usability (and the conversation as well). If you think that it's okay to display 5 licenses while there are only 3 available, and you think, that first prints and second prints are the same, then we are done here.

**Comment by Mike-E-angelo** [comment]
> I will tell him to go to hell

Again, perspective 🙃  That is what makes free markets so interesting and valuable, that you can create products with different features.  Some people care about the numbers, and others do not.  If you do not care about the numbers, good news, as you point out there are plenty of existing systems out there and you are free to see what they have to offer.

This system aims to be different from what has already been done, but also similar in terms of overall value.  If having intense discussions about the numbering of things is the worst we do, I would say we're doing pretty well. :)

> If you think that it's okay to display 5 licenses while there are only 3 available

I think I have stated that we're finding a way to convey several pieces of important data in a concise and accurate way.  There are five total yet 3 are remaining active for sale+resale.  How do we present this in a way so that when someone goes snooping through the licenses they do not open another issue (that takes another eight hours of "arguing" 🤣) stating that we have it all wrong?

> that first prints and second prints are the same

I did not say that.  Please revisit my comment.

**Comment by ujmappa** [comment]
I still say that first and second prints cannot and should not be counted together.

For the snooping around, I really don't get it. If there are 3 available licenses, then there are 3 available licenses that should be displayed. They can snoop around as much as they want, in license explorer it will be there that it was 5, revoked 2, in my math that is 3. There is no certain magic or fraud here. I mean, why on earth would someone display 5?!

I work in an enterprise environment. We have kinda node types, nodes, node connection types, node connections, node properties to handle very complicate user rights. Now all of these have history. Not just the log, but a copy of every state, so we can query the whole graph at a certain point of time, which is pretty great in troubleshooting. There is of course no delete from system perspective, even if delete operation is shown to the user. Now if someone asks me how many nodes are in the system, I will tell ca. 50.000, not 250.000 (with deleted), and especially not ca. 75.000.000 with one year history, and I will definetly not tell, that in overall it's close to 1TB on archive DB with another 14 years of history.

**Comment by Mike-E-angelo** [comment]
>  I mean, why on earth would someone display 5?!

Because there were 5 total actually produced and they are interested in this metric. :)  I hope you understand that I understand your side of the discussion here.  I am looking for a concise way to convey all information and appease all sides.

> , I will tell ca. 50.000, not 250.000 (with deleted), and especially not ca. 75.000.000 with one year history

I understand, this is a better comparison.  Thank you for sharing this.  Fundamentally, we are grappling with the view of a source and what is the best way to display that information that is accurate yet concise to the user and appeases the different viewpoints here? 🤔

**Comment by ujmappa** [comment]
We are really running in circles now. Choose the most accurate number that describes the count of licenses, and display that. You can dump the whole history of the issue on the bottom.

**Comment by Mike-E-angelo** [comment]
> Choose the most accurate number that describes the count of licenses

As will probably not be surprising to you, I feel the choice has already been made, and I will provide another example for you to consider.

You may know that a good deal of collectors prefer 1/1.  One of the early collectors of this application, artofasystem, is very much in preference of this and when I pointed out that there is a chance that the earliest issued licenses have a chance of becoming valuable due to their #, he went through and purchased all the remaining 1/1's in the system at the time.

Now consider that under your suggestion, that he was looking for 1/1's, and he learns upon closer inspection he didn't purchase a 1/1 but actually a 1/3 or 1/5 because the artist issued many but could only sell one, recalling the remaining.  I can bring him into this conversation to confirm but I have a high degree of confidence that he wouldn't like it as much as a true 1/1, and might even be disappointed with his purchase in light of such a fact.  As such, feel it is misrepresentative to mark it as 1/1 in such cases because there is more to the story than meets the eye which is what we are capturing when we say 1/n.

Along those lines, there are some further thoughts.  By saying 1/4 where 2 of them are actually recalled/revoked and still included in the total, there is a good deal of information there.  Some could look at this and say that the artist got impatient and recalled their inventory, rather than sticking to their guns and keeping it available and waiting for it to sell.  Now that is not a judgment call and happens all the time, but it's something that collectors can use to value a work based on the few characters of text used to convey it.  Other artists run out of capacity and sit on their hands until it sells (or purchase from other artists to get more capacity).  Indeed we find a great deal of artists in our system currently in such a painful state.  Again, not right or wrong, but "just is" and helps define the artist along with their approach, and the subsequent value a collector might imbue upon a potential product created by said artist.

Having that number outline the entire product lineage carries a good deal of information in a compact, easy-to-read manner and I feel it's better left in than changed.  However, I remain open to further thoughts and discussion about this, as always. 👍

**Comment by ujmappa** [comment]
Yeah, I will not spend this much time again, but thanks :)
