### ISSUE TITLE
Do not display archived

### ISSUE THREAD

**Issue by ujmappa** [StarbeamOne/home#114]
Recalled inventory items that are archived are still displayed on the inventory page

**Comment by ujmappa** [comment]
Also when I switch from tile mode to grid view there is a checkbox on bottom "Include archived inventory" while we have a switch on top, and the checkbox works reversed(?)

**Comment by Mike-E-angelo** [comment]
Thank you for reporting this.  Finally, something we can both agree on. :D  The Tile Mode is new and is a request.  Admittedly I rushed through it to get it to Done.  The `Display Archived` toggle is not supposed to show as denoted there is already one in the classical grid mode view.

Note that the switch/toggle causes some chaos with the grid view so this may be why you are seeing unexpected results (display does not refresh due to event timing).

I have published a fix please confirm at your earliest convenience 👍

**Comment by ujmappa** [comment]
It works now, but why isn't the handling the same? In tile mode we have a switch at the top, in grid mode we have a checkbox on the bottom... I guess both should be a switch at the top

**Comment by Mike-E-angelo** [comment]
It's not the same as they were developed at different times. :)  The grids all have the checkboxes for archived items at the bottom.  The reason it is at the top for tile mode is that a lot more scrolling is needed so it can easily get out of view and/or unseen/unknown.

**Comment by ujmappa** [comment]
Which basically means that you will change it to a switch at the top? Or it means, that they were developed at different times, so they are okay to differ?

**Comment by Mike-E-angelo** [comment]
The latter :)  We've got two states now, one from 4 years ago, and one from 2 months ago.  To consolidate means having a UX sweep at some point that does a better job of making things fast, pretty, and consistent.  Right now we're at "it's not entirely pretty but works" 😁

**Comment by ujmappa** [comment]
Aha. OK. Then case closed.
