### ISSUE TITLE
Reduce header items

### ISSUE THREAD

**Issue by ujmappa** [StarbeamOne/home#115]
"Welcome to Beta II", "Announcement", "About" and "Learn more" are okay on a landing page, but the header should not contain them (takes away the space). Also link to Gitbook should be moved to menu (and later the entire content should be moved to Starbeam pages). 

After that you could maybe make the Starbeam logo smaller to fit the height of the icons, this way the header would have a common height and all items could be displayed when scrolling (including the logo, or a smaller version of logo). Icons could be smaller as well to fit the width of a mobile view while you keep the outerHeight at the current value.

**Comment by Mike-E-angelo** [comment]
Good point about the announcement buttons.  I will see if I can get that done. 👍

**Comment by Mike-E-angelo** [comment]
I got the announcements moved to front page only. 👍

So for the GitBook, it already is in the menu under `Information -> Documentation`.  We really have spent a lot of time trying to call attention to the documentation, but people simply have a habit of ignoring help because of the anxiety it produces of the implied time investment.  It is up there with banner ads with ignored content.

As for fitting the icons w/ the logo are you talking desktop or mobile view?  I might need a wireframe or equivalent to have a better idea of what you are after here.

**Comment by Mike-E-angelo** [comment]
FWIW I have taken a stab at the header outside of the front page, reducing size of the logo & removing the `Digital Publishing Starship`, attempting to align it w/ the hud in desktop/tablet views.  I've also reduced the size of the primary menu navigation buttons.

**Comment by Mike-E-angelo** [comment]
I have not heard any additional comments so I am guessing this is OK 🤞  Otherwise please leave a comment and we can further discuss.
