### ISSUE TITLE
Capacity not maintained on inventory price change

### ISSUE THREAD

**Issue by ujmappa** [StarbeamOne/home#117]
I've tried to change the price for one of my items in inventory, but after raising it, the capacity was not decreased for appropriate market

**Comment by Mike-E-angelo** [comment]
Whoa, that is a bug.  I will look into this.  Thank you for reporting this. 👍

**Comment by Mike-E-angelo** [comment]
Boo, I am not sure what I was thinking here. 🤦‍♂️  My thought was that capacity is consumed at the time of publishing and is static.  If you lower capacity and sell you get the initially utilized capacity back.  However, without limits, someone could indeed publish at a lower price and then max out the price after the fact, effectively bypassing capacity limits by using market minimums.

Two options:
- Simple: I could cap the price at the original published price.  The issue here is that if someone makes a mistake they will not be able to correct it unless recalling.  We could wait for someone to report this before doing the below.  This can take < 1 hour.
- Complex: Add Price Change events to capacity accounts.  I would have to display the remaining capacity like the publishing and get it working in the new view.  But mostly it's model changes.  This can take up to 1.5 days after testing and everything else that I am up to.

What do you think @ujmappa should I take the easy or difficult route? 🤔

**Comment by ujmappa** [comment]
Almost every system allows to change the price. I usually prefer simple things, but here your simple solution is too restrictive and I don't think the "complex" solution is that complex if it can be done within 2 days. So I would choose option B.

**Comment by Mike-E-angelo** [comment]
I'm apt to agree with you, it's not that complex but everything seems that way from the outset. 😁  I am also balancing the schedule for Beta III which is already pretty tight, so that's my primary concern.  I'll see if I can get this done by EOD. 👍

**Comment by Mike-E-angelo** [comment]
Alright @ujmappa this is now in staging for your review: https://staging.starbeam.one

If it looks OK to you I will push it to production 👍

**Comment by ujmappa** [comment]
I cannot change the quantity of my issuance?

**Comment by ujmappa** [comment]
It is okay, one glitch is when I try to raise the price above capacity limit, it resets the editfield to 0 flares, and then all the handling there gets messy, cannot set it to 1.5 - Instead of resetting just keep it on the maxvalue.

**Comment by Mike-E-angelo** [comment]
Whoops!  Thank you for that.  I will investigate now.

**Comment by Mike-E-angelo** [comment]
Please try now. 👍

**Comment by ujmappa** [comment]
It's okay now, it can go to prod

**Comment by Mike-E-angelo** [comment]
Done.  Thank you again for all your valuable feedback!
