### ISSUE TITLE
Refresh Starbeam's fonts + unifying them

### ISSUE THREAD

**Issue by greenbrook** [StarbeamOne/home#84]
I noticed that Awesome (or Play) font doesn't belong to the modern and accessible font families. Also, we use 3+ font families on the platform whilst one font family would've been enough as our platform isn't devoted to fashion or graphic design in particular. 
I also noticed that our creator likes uppercase and letter spacing which I propose to review. As a single font family to unify the platform's type design, I currently propose Lato. Below on the screenshot I experimented with CSS, changed Play and Helvetica to Lato, removed uppercase and letter-spacing. 
I tried Helvetica first, but then I noticed that Lato has bigger letter-space than Helvetica by default, and it has to please our creator more :D Let's take a moment to appreciate how nice and sophisticated #MadeInMi looks with Lato and without the uppercase. Also, let me add here that Lato font was created by my international brother Łukasz Dziedzic, based in Warsaw. "Lato" means "summer" in Polish and I heard that someone here is a June lover :D 

<img width="1023" alt="Знімок екрана 2023-03-11 о 14 08 47" src="https://user-images.githubusercontent.com/125400168/224483975-93033cea-87cf-42b8-acf4-6363dee57db0.png">

**Comment by Mike-E-angelo** [comment]
Thank you for the suggestions!  I am very much open to all of them of course and as long as you let me know what direction you would like to go I am more than certain to agree with it.  As mentioned I really feel I am a placeholder to "keep the lights on" until someone can take over and make this sing.

> I also noticed that our creator likes uppercase

This is actually a good point/question/inquiry.  I do not have a preference for upper case, and if it exists it's due to the template used.  However, now that I have looked at it for 3 years counting now, I have grown attached to those areas that are uppercased. 🤔

That stated I like the new look.

So is the idea here to remove all font families except for Lato/Summer/June? :)  I can do this if so. 👍

**Comment by Mike-E-angelo** [comment]
Deployed to staging for review: https://staging.starbeam.one/

**Comment by greenbrook** [comment]
What do you think? Isn't it beautiful? :) I'm about the staging ) 
I really think that using more than one or two typefaces gives unnecessary complexity to the platform design. Human eye likes the simplicity and neutrality of the type, and a finished unified look that is created when a single typeface is preferred. It brings the feeling of clarity. And it makes CSS easier and cleaner.

**Comment by Mike-E-angelo** [comment]
I totally agree and you will get no discussion from me.  The reason why we have more than one font was that I was _totally_ geeking out 3 years ago with all the "new" web tech such as fonts.  I really really _really_ loved how many fonts are available now and how easy it was to implement.  I've since adjusted and don't care about it as much anymore.  Still cool though :)

**Comment by greenbrook** [comment]
Ow yeah, I totally understand the love for diversity and chaos :D

**Comment by Mike-E-angelo** [comment]
This has been accomplished please confirm when you get the chance and close out this issue @greenbrook 👍🙏

**Comment by Mike-E-angelo** [comment]
I guess that's a yes. :P
